### ISSUE TITLE
@Awake(BEFORE_DISABLE)和@Awake(DISABLE)无法正常使用

### ISSUE THREAD

**Issue by Mikoto-qiuhua** [Glom-c/Pouvoir#6]
![image](https://user-images.githubusercontent.com/102891248/226261756-3f46a6ee-ece4-4396-8037-49d6f627efcc.png)
![image](https://user-images.githubusercontent.com/102891248/226261781-f17ce556-18e2-4871-8c6e-55e0e7756376.png)

**Comment by Glom-c** [comment]
新版修了
